name: CI

on:
    push:
        branches:
            - main

jobs:
    install-dependencies:
        name: Install Dependencies
        runs-on: ubuntu-latest
        outputs:
            cache-key: ${{ steps.cache-deps.outputs.cache-key }}
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            # Caching dependencies
            - name: Cache Bun dependencies
              id: cache-deps
              uses: actions/cache@v3
              with:
                  path: .bun
                  key: bun-deps-${{ hashFiles('bun.lockb') }}
                  restore-keys: |
                      bun-deps-

            # Install dependencies
            - name: Install dependencies
              run: bun install

    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            # Reuse the cache from the install-dependencies job
            - name: Restore Bun cache
              uses: actions/cache@v3
              with:
                  path: .bun
                  key: ${{ needs.install-dependencies.outputs.cache-key }}

            # Run the lint command
            - run: bun run lint

    build:
        name: Build Project
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            # Reuse the cache from the install-dependencies job
            - name: Restore Bun cache
              uses: actions/cache@v3
              with:
                  path: .bun
                  key: ${{ needs.install-dependencies.outputs.cache-key }}

            # Run the build command
            - run: bun run build
